### ISSUE TITLE
Gnome Shell - Unreadable clock font color

### ISSUE THREAD

**Issue by btd1337** [paullinuxthemer/Telinkrin-GTK#15]
In Gnome 3.32 the clock font color is unreadable.

![Captura de tela de 2019-03-16 18-22-09](https://user-images.githubusercontent.com/11943860/54481875-504b3880-4819-11e9-9ca8-1d74a41a7e4f.png)

**Comment by inflop** [comment]
Same here.
![printscreen](https://user-images.githubusercontent.com/7738902/58372450-9b6e7f80-7f1d-11e9-9dad-1d4b2d88e8ef.jpg)

**Comment by inflop** [comment]
Edit gnome-shell.css, change color at line below and save:
![image](https://user-images.githubusercontent.com/7738902/58668980-f4358200-833a-11e9-8939-bdb6115ccaef.png)
